### ISSUE TITLE
New files in a directory managed by stow

### ISSUE THREAD

**Issue by gudstrand** [aspiers/stow#109]
I am wondering what the ideal workflow would be in this case.

I have a newvim config in ~/.config/nvim/. Under that directory there is a lua/plugins dir that has several config files (one per plugin). I added all of my cohfig files to stow using the --adopt flag and everything worked as expected. 

Later,I add a couple new plugins and configured them by adding a config file for each in the ./config/nvim/lua/plugins directory. Can I just "adopt" the new files into stow? If so, how?

**Comment by aspiers** [comment]
I don't quite follow - what are your stow dir and package dir in this scenario?

**Comment by lgrosz** [comment]
The `~/.config/nvim` is usually the symlink created by Stow to your neovim config. I'm pretty sure at this point you're out of Stow's responsibility. The config files you've added should be source controlled however you plan on source controlling your config. -- Unless you're using Stow in a completely different way than people usually do to manage their dotfiles..

**Comment by gudstrand** [comment]
I am not sure what was going on but after a reboot things seems to be working as expected. I can now add the new files to git and commit. So far so good.

**Comment by aspiers** [comment]
Sounds good, marking closed but we can reopen if there are still issues.
