### ISSUE TITLE
Document TeX dependency

### ISSUE THREAD

**Issue by sirg** [aspiers/stow#110]
Based on the functionality described, I cannot see a logical reason why stow depends on TeX. 

But if it's going to be dependent on TeX, it should clearly say so up front rather than leaving me to discover this as a result of a failed build.

**Comment by aspiers** [comment]
Yes exactly.  Let's keep this issue open to address updating the docs about this dependency, and #95 for removing the dependency.

**Comment by aspiers** [comment]
Should be fixed by #117.
