### ISSUE TITLE
Precedence warning message appears in 2.4.0

### ISSUE THREAD

**Issue by Thomas-Philippot** [aspiers/stow#115]
After a system update stow now display a warning : `Possible precedence issue with control flow operator (exit) at /usr/bin/stow line 839, <DATA> line 23.`

Everything seems to work fine, but the error message is always there.

My system :
- Arch Linux (kernel 6.10.8)
- Stow version 2.4.0

**Comment by aspiers** [comment]
This is a duplicate of #113; see https://github.com/aspiers/stow/pull/113#issuecomment-2305940941.
