### ISSUE TITLE
FTBS: on newer perl versions -- pod2man fails because it now needs a --name parameter when in pipeline

### ISSUE THREAD

**Issue by Corin-EU** [aspiers/stow#18]
With perl v5.20.2 (eg on Debian 8.6), the latest version of stow r.c171ca8 builds just fine.

However, with a more  uptodate recent version of perl v5.22.1 (eg on Linux Mint 18, Ubuntu 16.04), building of the manual page fails.

    [ -d doc ] || mkdir doc # required in vpath mode
    sed -e 's|[@]PERL[@]|/usr/bin/perl|g' -e 's|[@]VERSION[@]|2.2.2|g' -e   "s|[@]USE_LIB_PMDIR[@]|$use_lib_pmdir|g" < bin/stow.in | pod2man > doc/stow.8
    IO::File=IO(0x829a3c4) around line 1: No name given for document
    POD document had syntax errors at /usr/bin/pod2man line 68.
    Makefile:1530: recipe for target 'doc/stow.8' failed
    make: *** [doc/stow.8] Error 255

Thanks to **Robert Munteanu** providing the solution on [Stackoverflow](http://stackoverflow.com/questions/38425732/pod2man-fails-with-no-name-given-for-document), adding a --name parameter with a document name (eg stow.8) resolves the issue.

Here is a patch to Makefile.am to add the necessary parameter to pod2man

[001_Makefile.am.patch.txt](https://github.com/aspiers/stow/files/483063/001_Makefile.am.patch.txt)

As --name is not compulsory for pod2man, it seems that it is because of the pipeline being used that the newer version of pod2man now falls over. 

Splitting the line into two and using a temporary file

     sed -e 's|[@]PERL[@]|/usr/bin/perl|g' -e 's|[@]VERSION[@]|2.2.2|g' -e "s|[@]USE_LIB_PMDIR[@]|$use_lib_pmdir|g" < bin/stow.in > XXX
     
     pod2man XXXtmpfileXXX > doc/stow.8

works just fine without giving pod2man the --name stow.8 parameter, whereas 

    cat XXXtmpfileXXX | pod2man

complains with 

    IO::File=IO(0x9420284) around line 1: No name given for document

**Comment by aspiers** [comment]
Thanks a lot for the great report!  I had to tweak your patch slightly to get the right name and section.
