### ISSUE TITLE
remove dependency on unmaintained texi2html

### ISSUE THREAD

**Issue by aspiers** [aspiers/stow#21]
As originally mentioned in http://lists.gnu.org/archive/html/info-stow/2016-11/msg00004.html:

`texi2html` is [part of the Texinfo source repository](http://svn.savannah.gnu.org/viewvc/trunk/texi2html/?root=texinfo) but apparently [it's no longer maintained](http://www.nongnu.org/texi2html/) and not included in the Texinfo distribution.

Despite that, some distributions do include it within their `texinfo` packages, e.g. [openSUSE](https://build.opensuse.org/package/view_file/openSUSE:Leap:42.2/texinfo/texinfo.spec?expand=1),
from which you can see that the separate distributions are still available, but [have not been updated since 2010](http://download.savannah.nongnu.org/releases/texi2html).

However there is [a partially compatible drop-in replacement which is a simple wrapper around `texi2any`](http://git.savannah.gnu.org/cgit/texinfo.git/tree/util/texi2html) (also [an outdated svn link](http://svn.savannah.gnu.org/viewvc/trunk/util/texi2html?root=texinfo&view=markup)).  Perhaps we need to convert the build process to use that.  I have no idea how well it would work right now.

**Comment by gbpoole** [comment]
May I ask: why is this closed?  I tried to build from a Github clone today on an up-to-date CentOS system, and am failing with the following:

```
> make
[ -d doc ] || mkdir doc # required in vpath mode
rm -f doc/manual-single.html
texi2html --P=. --output=doc/manual-single.html -expandinfo -menu -monolithic -verbose doc/stow.texi
make: texi2html: Command not found
make: *** [doc/manual-single.html] Error 127```

Tried to build `texi2html` and that was its own set of problems.  Seems to me that it would be nice if `configure` caught that `texi2html` was not present and then didn't try to build the documentation.  Alternatively, an option to build without docs would be nice.

**Comment by aspiers** [comment]
@gbpoole It's not closed 😉 Do you have time to try the replacement which I referenced above?

**Comment by gbpoole** [comment]
Thanks for the quick response ... and sorry for the delay getting back to you ... been traveling.

I'm getting the following error now:

```
Live child 0x7f8827d0b780 (doc/manual-single.html) PID 60581
Reaping winning child 0x7f8827d0b780 PID 60581
rm -f doc/manual-single.html
Live child 0x7f8827d0b780 (doc/manual-single.html) PID 60585
Reaping winning child 0x7f8827d0b780 PID 60585
texi2html --P=. --output=doc/manual-single.html -expandinfo -menu -monolithic -verbose doc/stow.texi
Live child 0x7f8827d0b780 (doc/manual-single.html) PID 60587
Unknown option: set-init-variable
Reaping losing child 0x7f8827d0b780 PID 60587
make: *** [doc/manual-single.html] Error 1
Removing child 0x7f8827d0b780 PID 60587 from chain.
```

I'm using  gnu`texinfo` (https://savannah.gnu.org/projects/texinfo; version 6.6) for my installation of `texi2any`.

As a work around, I've found that if I just create an an empty executable script in my path called `texi2htm` (rather than the script you link to above) then it just does nothing and passes that build step, proceeding to completion.

All a bit of a kludgy fix but I guess it can do for now.  Cheers.

**Comment by aspiers** [comment]
I found https://www.gnu.org/software/texinfo/manual/texinfo/html_node/texi2html.html#texi2html which documents the wrapper around `texi2any`, and I'm working on converting the build to that.  In the process I discovered [a bug in the wrapper](https://lists.gnu.org/archive/html/bug-texinfo/2019-06/msg00010.html).
