### ISSUE TITLE
There is no release with this wonderful pull request that was merged over a year ago

### ISSUE THREAD

**Issue by rwa** [aspiers/stow#26]
https://github.com/aspiers/stow/pull/17

**Comment by aspiers** [comment]
Acknowledged and thanks for the nudge.  As I mentioned [here](https://github.com/aspiers/stow/issues/3#issuecomment-358815209), my next batch of Stow work is long overdue and when it finally comes I'll certainly make a proper release!  I'm off on holiday on Sunday though, so it won't be for a while I'm afraid.

**Comment by lassik** [comment]
This feature uses `dot-` as a prefix for dotfile directories. At least in BSD-land the usual prefix is `dot.` Examples:

* https://github.com/openbsd/src/tree/master/etc/root
* https://github.com/freebsd/freebsd/tree/master/share/skel

I also found these files on my Mac: `dot.mg` and `dot.gdbinit`.

On the other hand, in one Emacs package I found `dot-emacs.el`.

On Alpine Linux or Ubuntu I didn't find any files with either prefix.

**Comment by aspiers** [comment]
I can only apologise that it's another year on and I haven't got around to this.  I haven't forgotten though!

**Comment by aspiers** [comment]
A bit of good news: thanks to sponsorship from SUSE, this week I'm working on catching up with Stow maintainership, and hope to make a new release:

https://hackweek.suse.com/18/projects/catch-up-on-gnu-stow-maintenance

**Comment by aspiers** [comment]
Stow 2.3.0 is now released. I'll send an announcement to the mailing lists tomorrow.
