### ISSUE TITLE
please clarify why there isn't a version 2.3.0 release

### ISSUE THREAD

**Issue by m040601** [aspiers/stow#31]
This is important because of the new "--dotfiles" option.
I searched the entire Internet the best as I could, can't find an answer
Apologies if I missed something.

in 2016:
> http://git.savannah.gnu.org/cgit/stow.git/commit/?id=94b155d99b9276d9ead42f5fd2ed88663dca39c1
> author | Adam Spiers <stow@adamspiers.org> | 2016-11-20 21:45:17 +0000
> +* Changes in version 2.3.0
> +** New --dotfiles option

in 2017:
> [Stow-devel] Release 2.3.0?
> http://lists.gnu.org/archive/html/stow-devel/2017-10/msg00000.html
> Date:	Fri, 27 Oct 2017 23:12:56 +0200
> Hi,Would it be possible to have 2.3.0 released?
> Regards, Leo

in 2018:
> https://savannah.gnu.org/bugs/?54272
> Submitted on: 	Sun 08 Jul 2018 09:30:10 PM UTC
> GNU Stow - Bugs: bug #54272, Version 2.3.0 untagged [Savannah]
> I would like to second that a new release be made.

**Comment by m040601** [comment]
Please ignore this issue I opened.
It was already open here in Github .... right under my nose.

https://github.com/aspiers/stow/issues/3
>  commented on Jan 18, 2018
> ... I'm incredibly busy at the moment...I can't look at this more closely right now.


https://github.com/aspiers/stow/issues/26

> commented on Jan 19, 2018
> ... work is long overdue and when it finally comes I'll certainly make a proper release!
>

**Comment by aspiers** [comment]
A bit of good news: thanks to sponsorship from SUSE, this week I'm working on catching up with Stow maintainership, and hope to make a new release:

https://hackweek.suse.com/18/projects/catch-up-on-gnu-stow-maintenance

Sorry again for the delay!
