### ISSUE TITLE
Empty STOW_DIR can make un-expected behavior

### ISSUE THREAD

**Issue by Gnouc** [aspiers/stow#6]
Currently, empty STOW_DIR cause stow dir to be set to user home directory, specified by `$ENV{HOME}` variable:
```
$ pwd
/tmp
$ STOW_DIR= stow -v3 -n -D vim74
Possible precedence issue with control flow operator at /usr/share/perl5/Stow.pm line 1736.
Use of chdir('') or chdir(undef) as chdir() is deprecated at /usr/share/perl5/Stow/Util.pm line 183, <DATA> line 18.
stow dir is /home/cuonglm
stow dir path relative to target . is ../home/cuonglm
cwd now .
stow: ERROR: The stow directory ../home/cuonglm does not contain package vim74 (No such file or directory)
```

This can lead to un-expected behavior and security problem.

This [pull request](https://github.com/aspiers/stow/pull/5) fix the issue by setting stow dir to current working directory and give a message warning.

**Comment by Gnouc** [comment]
We can also document this behavior to prevent user from confusing.

**Comment by aspiers** [comment]
Thanks!  The manual says:

    Defaults to the value of the environment
    variable @env{STOW_DIR} if set, or the current directory otherwise.

so I think it should already be clear.
