### ISSUE TITLE
dotfiles option not working with .config folder

### ISSUE THREAD

**Issue by chgallen** [aspiers/stow#73]
Suppose you have a package "app", which keeps its configurations settings in ~/.config/app/settings.json.

Let's say you want to use stow to keep the app's settings file in a ~/dotfiles/ directory, and create a symlink from the home folder. You want to use the `--dotfiles` option so that the dotfiles directory isn't full of hidden files. So you move the configuration settings to ~/dotfiles/app/dot-config/app/settings.json and then run `stow --dotfiles app` from the dotfiles directory to create the symlinks.

I think this should work, but it raises the error: `stow: ERROR: stow_contents() called with non-directory path: dotfiles/app/.config`.

Have I made an error, or is this a bug?

Reproducible code:

```
#!/bin/bash

# Set up
mkdir -p homedir/.config
mkdir -p homedir/dotfiles/app/dot-config/app
touch homedir/dotfiles/app/dot-config/app/settings.json
cd homedir/dotfiles

# Doesn't work!
stow --dotfiles app

# Tidy up
cd ../..
rm -r homedir
```

**Comment by EliaGeretto** [comment]
Duplicate of #33?

**Comment by chgallen** [comment]
Yes! Oops, closing now
