### ISSUE TITLE
stow can not work with trailing and leading space directory

### ISSUE THREAD

**Issue by Gnouc** [aspiers/stow#8]
Stow currently will not work with some directories contains trailing and leading spaces, that because the `sanitize_path_options` removed those spaces:
```
    if (exists $options->{dir}) {
        $options->{dir}    =~ s/\A +//;
        $options->{dir}    =~ s/ +\z//;
    }
```

and:
```
    if (exists $options->{target}) {
        $options->{target} =~ s/\A +//;
        $options->{target} =~ s/ +\z//;
        usage("--target value '$options->{target}' is not a valid directory")
            unless -d $options->{target};

    }
```

So with two distinct directories `" 123"` and `"123"`, stow will treat them as the same.

I'm not sure it's intended behavior or not. I attempted a [commit](https://github.com/Gnouc/stow/commit/b4a7c3e534b35b3d8c05126cc28c05fc10620cc5) to fix it. If it's okay, I will go with a pull request.

**Comment by aspiers** [comment]
Yes, I don't know why that is there.  I'm not even sure I wrote that code.  Please submit the PR.  Thanks!

**Comment by Gnouc** [comment]
This [pull](https://github.com/aspiers/stow/pull/9) fixed this problem.
