### ISSUE TITLE
`stow --simulate` should show `--adopt` actions

### ISSUE THREAD

**Issue by ilyagr** [aspiers/stow#81]
Currently, running `stow --simulate` does not report files that would be adopted with `--adopt`. For example,

```
$ mkdir -p stow/test && cd stow
$ echo Text > ../file
$ touch test/file
$ stow --adopt test --simulate
WARNING: in simulation mode so not modifying filesystem.
```

No actions that `stow` would perform are reported, even though actually running  `stow --adopt test` would adopt the file `file`:

```
$ stow -v --adopt test
MV: file -> stow/test/file
LINK: file => stow/test/file
```

**Comment by ilyagr** [comment]
Never mind. I realized `--simulate` is useless without `-v`.

**Comment by tarikwaleed** [comment]
got the error `stow: ERROR: slashes are not permited in package names` when using `stow --simulate -v --target=/path/to/target/tree /path/to/source/tree
what wrong I'm doing??
