### ISSUE TITLE
Request build flag to turn off docs creation

### ISSUE THREAD

**Issue by gbpoole** [aspiers/stow#95]
May I humbly request a build switch that would allow us to build and install Stow while skipping the build of the docs. Having to build latex to build Stow is very wasteful and frustrating for my use case.

**Comment by gbpoole** [comment]
I run Stow on a lot of different systems and I often run into the sort of build errors reported in issue #96 

Latex distributions can differ significantly and this sort of thing really adds to the frustration of always needing to build the docs.

**Comment by aspiers** [comment]
Yes this is a perfectly reasonable request.

**Comment by aspiers** [comment]
Looking into this now ... it seems that `makeinfo` (used to build the manual in Info and HTML format) does not depend on `texinfo`, and therefore doesn't depend on LaTeX either.  So I think we can keep building of `stow.info` by default, and make just building of the PDF optional.
